const test = require('node:test');
const assert = require('node:assert/strict');
const { calculateOverview } = require('../src/services/analyticsService');

function records() { return { payments: [{ _id: 'p1', amount: 10000, status: 'FAILED', failure: { code: 'insufficient_funds' } }, { _id: 'p2', amount: 5000, status: 'CAPTURED', failure: {} }, { _id: 'p3', amount: 20000, status: 'FAILED', failure: { code: 'card_declined' } }], recoveryCases: [{ _id: 'c1', payment: 'p1', status: 'DETECTED', recoveredAmount: 0 }, { _id: 'c2', payment: 'p2', status: 'CLOSED', recoveredAmount: 0 }, { _id: 'c3', payment: 'p3', status: 'RECOVERED', recoveredAmount: 20000 }], recoveryActions: [{ recoveryCase: 'c1', type: 'CUSTOMER_REMINDER', status: 'EXECUTED', execution: { providerReference: 'plink_1' } }, { recoveryCase: 'c1', type: 'RETRY_PAYMENT', status: 'BLOCKED' }, { recoveryCase: 'c3', type: 'CUSTOMER_REMINDER', status: 'EXECUTED', execution: { providerReference: 'plink_3' } }, { recoveryCase: 'c1', type: 'CUSTOMER_REMINDER', status: 'FAILED' }], auditEvents: [{ recoveryCase: 'c3', type: 'RECOVERY_COMPLETED', actor: 'RAZORPAY' }, { recoveryCase: 'c1', type: 'AI_FALLBACK_USED', actor: 'SYSTEM' }] }; }

test('overview derives truthful metrics from persisted records', () => { const m = calculateOverview(records()); assert.equal(m.revenueAtRisk, 10000); assert.equal(m.eligibleRecoveryCases, 1); assert.equal(m.recoveryAttempts, 3); assert.equal(m.successfulRecoveries, 1); assert.equal(m.recoveredRevenue, 20000); assert.equal(m.recoveryRate, 0.5); assert.equal(m.recoveryValueRate, 0.6667); assert.equal(m.blockedActions, 1); assert.equal(m.failedExecutions, 1); assert.equal(m.aiFallbacks, 1); assert.equal(m.breakdown.recoveryAction.CUSTOMER_REMINDER, 3); assert.equal(m.breakdown.failureCategory.TEMPORARY, 1); });
test('a created payment link without provider completion evidence never counts as recovered', () => { const data = records(); data.recoveryCases[2].status = 'ACTION_PENDING'; data.auditEvents = []; const m = calculateOverview(data); assert.equal(m.successfulRecoveries, 0); assert.equal(m.recoveredRevenue, 0); });
test('zero cases produce finite zero rates', () => { const m = calculateOverview({}); assert.equal(m.revenueAtRisk, 0); assert.equal(m.recoveryRate, 0); assert.equal(m.recoveryValueRate, 0); });
test('merchant-isolated data cannot contribute to another overview', () => { const a = calculateOverview({ payments: [{ _id: 'p', amount: 100, status: 'FAILED' }], recoveryCases: [{ _id: 'c', payment: 'p', status: 'DETECTED' }] }); const b = calculateOverview({}); assert.equal(a.revenueAtRisk, 100); assert.equal(b.revenueAtRisk, 0); });
