const PAYMENT_STATUS = Object.freeze({
  CREATED: 'CREATED',
  ATTEMPTED: 'ATTEMPTED',
  AUTHORIZED: 'AUTHORIZED',
  CAPTURED: 'CAPTURED',
  FAILED: 'FAILED'
});

const RECOVERY_CASE_STATUS = Object.freeze({
  DETECTED: 'DETECTED',
  DIAGNOSED: 'DIAGNOSED',
  RECOMMENDED: 'RECOMMENDED',
  POLICY_ALLOWED: 'POLICY_ALLOWED',
  POLICY_BLOCKED: 'POLICY_BLOCKED',
  ACTION_PENDING: 'ACTION_PENDING',
  ACTION_EXECUTING: 'ACTION_EXECUTING',
  RECOVERED: 'RECOVERED',
  UNRECOVERED: 'UNRECOVERED',
  CLOSED: 'CLOSED'
});

const RECOVERY_ACTION_TYPE = Object.freeze({
  RETRY_PAYMENT: 'RETRY_PAYMENT',
  PAYMENT_METHOD_UPDATE: 'PAYMENT_METHOD_UPDATE',
  CUSTOMER_REMINDER: 'CUSTOMER_REMINDER',
  ESCALATE_TO_HUMAN: 'ESCALATE_TO_HUMAN',
  NO_ACTION: 'NO_ACTION'
});

const RECOVERY_ACTION_STATUS = Object.freeze({
  RECOMMENDED: 'RECOMMENDED',
  POLICY_ALLOWED: 'POLICY_ALLOWED',
  POLICY_BLOCKED: 'POLICY_BLOCKED',
  BLOCKED: 'BLOCKED',
  QUEUED: 'QUEUED',
  EXECUTING: 'EXECUTING',
  EXECUTED: 'EXECUTED',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED'
});

const POLICY_DECISION = Object.freeze({
  NOT_EVALUATED: 'NOT_EVALUATED',
  ALLOWED: 'ALLOWED',
  BLOCKED: 'BLOCKED'
});

const ACTOR_TYPE = Object.freeze({
  SYSTEM: 'SYSTEM',
  MERCHANT_ADMIN: 'MERCHANT_ADMIN',
  AI_AGENT: 'AI_AGENT',
  RAZORPAY: 'RAZORPAY'
});

const AUDIT_EVENT_TYPE = Object.freeze({
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_AUTHORIZED: 'PAYMENT_AUTHORIZED',
  PAYMENT_CAPTURED: 'PAYMENT_CAPTURED',
  RECOVERY_CASE_CREATED: 'RECOVERY_CASE_CREATED',
  RECOVERY_CASE_CLOSED: 'RECOVERY_CASE_CLOSED',
  AI_DIAGNOSIS_RECORDED: 'AI_DIAGNOSIS_RECORDED',
  AI_ANALYSIS_STARTED: 'AI_ANALYSIS_STARTED',
  AI_RECOMMENDATION_GENERATED: 'AI_RECOMMENDATION_GENERATED',
  AI_PROVIDER_FAILED: 'AI_PROVIDER_FAILED',
  AI_FALLBACK_USED: 'AI_FALLBACK_USED',
  ACTION_RECOMMENDED: 'ACTION_RECOMMENDED',
  POLICY_EVALUATED: 'POLICY_EVALUATED',
  ACTION_EXECUTION_STARTED: 'ACTION_EXECUTION_STARTED',
  ACTION_EXECUTION_BLOCKED: 'ACTION_EXECUTION_BLOCKED',
  ACTION_EXECUTION_COMPLETED: 'ACTION_EXECUTION_COMPLETED',
  ACTION_EXECUTION_FAILED: 'ACTION_EXECUTION_FAILED',
  RECOVERY_PARTIAL_PAYMENT: 'RECOVERY_PARTIAL_PAYMENT',
  RECOVERY_COMPLETED: 'RECOVERY_COMPLETED',
  POLICY_UPDATED: 'POLICY_UPDATED'
});

const WEBHOOK_EVENT_STATUS = Object.freeze({
  RECEIVED: 'RECEIVED',
  PROCESSED: 'PROCESSED'
});

// Single application role for this increment. Kept as an enum (rather than a
// free-text field) so authorization checks never compare against ad-hoc strings.
const USER_ROLE = Object.freeze({
  MERCHANT_ADMIN: 'MERCHANT_ADMIN'
});

// Statuses that represent a RecoveryCase which is still being worked, as
// opposed to a terminal outcome. Used by the "OPEN" convenience filter and by
// the recovery intelligence service's eligibility check.
const OPEN_RECOVERY_CASE_STATUSES = Object.freeze(
  Object.values(RECOVERY_CASE_STATUS).filter(
    (status) => ![RECOVERY_CASE_STATUS.RECOVERED, RECOVERY_CASE_STATUS.UNRECOVERED, RECOVERY_CASE_STATUS.CLOSED].includes(status)
  )
);

module.exports = {
  PAYMENT_STATUS,
  RECOVERY_CASE_STATUS,
  RECOVERY_ACTION_TYPE,
  RECOVERY_ACTION_STATUS,
  POLICY_DECISION,
  ACTOR_TYPE,
  AUDIT_EVENT_TYPE,
  WEBHOOK_EVENT_STATUS,
  USER_ROLE,
  OPEN_RECOVERY_CASE_STATUSES
};
